export const placeholderProducts = [
  {
    id: 1,
    slug: "mcqueen-oversized-sneakers",
    name: "Oversized Sneakers",
    brand: "Alexander McQueen",
    brandSlug: "alexander-mcqueen",
    category: "shoes",
    categorySlug: "shoes",
    price: 590,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80",
    redirectUrl: "https://example.com/product/mcqueen-oversized-sneakers",
    tags: ["trending"],
    merchant: "Farfetch",
  },
  {
    id: 2,
    slug: "kenzo-tiger-sweatshirt",
    name: "Tiger Embroidered Sweatshirt",
    brand: "Kenzo",
    brandSlug: "kenzo",
    category: "clothing",
    categorySlug: "clothing",
    price: 285,
    originalPrice: 380,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&q=80",
    redirectUrl: "https://example.com/product/kenzo-tiger-sweatshirt",
    tags: ["sale"],
    merchant: "SSENSE",
  },
  {
    id: 3,
    slug: "michael-kors-jet-set-tote",
    name: "Jet Set Travel Tote",
    brand: "Michael Kors",
    brandSlug: "michael-kors",
    category: "bags",
    categorySlug: "bags",
    price: 298,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80",
    redirectUrl: "https://example.com/product/michael-kors-jet-set-tote",
    tags: ["trending"],
    merchant: "Michael Kors",
  },
  {
    id: 4,
    slug: "burberry-trench-coat",
    name: "Kensington Heritage Trench Coat",
    brand: "Burberry",
    brandSlug: "burberry",
    category: "clothing",
    categorySlug: "clothing",
    price: 2290,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
    redirectUrl: "https://example.com/product/burberry-trench-coat",
    tags: ["trending"],
    merchant: "Burberry",
  },
  {
    id: 5,
    slug: "fendi-baguette-bag",
    name: "Baguette Shoulder Bag",
    brand: "Fendi",
    brandSlug: "fendi",
    category: "bags",
    categorySlug: "bags",
    price: 1890,
    originalPrice: 2490,
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&q=80",
    redirectUrl: "https://example.com/product/fendi-baguette-bag",
    tags: ["sale"],
    merchant: "Net-a-Porter",
  },
  {
    id: 6,
    slug: "gucci-horsebit-loafers",
    name: "Horsebit Leather Loafers",
    brand: "Gucci",
    brandSlug: "gucci",
    category: "shoes",
    categorySlug: "shoes",
    price: 890,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80",
    redirectUrl: "https://example.com/product/gucci-horsebit-loafers",
    tags: ["trending"],
    merchant: "Gucci",
  },
  {
    id: 7,
    slug: "prada-re-nylon-jacket",
    name: "Re-Nylon Cropped Jacket",
    brand: "Prada",
    brandSlug: "prada",
    category: "clothing",
    categorySlug: "clothing",
    price: 1650,
    originalPrice: 2100,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
    redirectUrl: "https://example.com/product/prada-re-nylon-jacket",
    tags: ["sale"],
    merchant: "Prada",
  },
  {
    id: 8,
    slug: "nike-air-max-97",
    name: "Air Max 97 Gold Bullet",
    brand: "Nike",
    brandSlug: "nike",
    category: "shoes",
    categorySlug: "shoes",
    price: 175,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    redirectUrl: "https://example.com/product/nike-air-max-97",
    tags: ["trending"],
    merchant: "Nike",
  },
  {
    id: 9,
    slug: "zara-satin-midi-dress",
    name: "Satin Midi Dress",
    brand: "Zara",
    brandSlug: "zara",
    category: "clothing",
    categorySlug: "clothing",
    price: 69,
    originalPrice: 99,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80",
    redirectUrl: "https://example.com/product/zara-satin-midi-dress",
    tags: ["sale"],
    merchant: "Zara",
  },
  {
    id: 10,
    slug: "hm-wool-blend-blazer",
    name: "Wool Blend Oversized Blazer",
    brand: "H&M",
    brandSlug: "hm",
    category: "clothing",
    categorySlug: "clothing",
    price: 59,
    originalPrice: 89,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    redirectUrl: "https://example.com/product/hm-wool-blend-blazer",
    tags: ["sale"],
    merchant: "H&M",
  },
  {
    id: 11,
    slug: "mango-leather-crossbody",
    name: "Quilted Leather Crossbody",
    brand: "Mango",
    brandSlug: "mango",
    category: "bags",
    categorySlug: "bags",
    price: 79,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    redirectUrl: "https://example.com/product/mango-leather-crossbody",
    tags: ["new"],
    merchant: "Mango",
  },
  {
    id: 12,
    slug: "adidas-ultraboost-22",
    name: "Ultraboost 22 Running Shoes",
    brand: "Adidas",
    brandSlug: "adidas",
    category: "shoes",
    categorySlug: "shoes",
    price: 140,
    originalPrice: 190,
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80",
    redirectUrl: "https://example.com/product/adidas-ultraboost-22",
    tags: ["sale"],
    merchant: "Adidas",
  },
  {
    id: 13,
    slug: "gucci-marmont-mini-bag",
    name: "GG Marmont Mini Bag",
    brand: "Gucci",
    brandSlug: "gucci",
    category: "bags",
    categorySlug: "bags",
    price: 1290,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1575032617751-6ddec2089882?w=600&q=80",
    redirectUrl: "https://example.com/product/gucci-marmont-mini-bag",
    tags: ["trending"],
    merchant: "Mytheresa",
  },
  {
    id: 14,
    slug: "little-marc-jacobs-snapshot-bag",
    name: "The Snapshot Camera Bag",
    brand: "Little Marc Jacobs",
    brandSlug: "little-marc-jacobs",
    category: "bags",
    categorySlug: "bags",
    price: 325,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80",
    redirectUrl: "https://example.com/product/little-marc-jacobs-snapshot-bag",
    tags: ["new"],
    merchant: "Nordstrom",
  },
  {
    id: 15,
    slug: "burberry-check-scarf",
    name: "Giant Check Cashmere Scarf",
    brand: "Burberry",
    brandSlug: "burberry",
    category: "clothing",
    categorySlug: "clothing",
    price: 520,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80",
    redirectUrl: "https://example.com/product/burberry-check-scarf",
    tags: ["new"],
    merchant: "Burberry",
  },
  {
    id: 16,
    slug: "fendi-gold-earrings",
    name: "F is Fendi Gold Drop Earrings",
    brand: "Fendi",
    brandSlug: "fendi",
    category: "jewellery",
    categorySlug: "jewellery",
    price: 490,
    originalPrice: 650,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
    redirectUrl: "https://example.com/product/fendi-gold-earrings",
    tags: ["sale"],
    merchant: "Farfetch",
  },
  {
    id: 17,
    slug: "prada-chain-necklace",
    name: "Eternal Gold Chain Necklace",
    brand: "Prada",
    brandSlug: "prada",
    category: "jewellery",
    categorySlug: "jewellery",
    price: 2800,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    redirectUrl: "https://example.com/product/prada-chain-necklace",
    tags: [],
    merchant: "Prada",
  },
  {
    id: 18,
    slug: "nike-dunk-low-panda",
    name: "Dunk Low Retro Panda",
    brand: "Nike",
    brandSlug: "nike",
    category: "shoes",
    categorySlug: "shoes",
    price: 110,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&q=80",
    redirectUrl: "https://example.com/product/nike-dunk-low-panda",
    tags: ["new"],
    merchant: "Nike",
  },
  {
    id: 19,
    slug: "zara-pearl-bracelet",
    name: "Faux Pearl Link Bracelet",
    brand: "Zara",
    brandSlug: "zara",
    category: "jewellery",
    categorySlug: "jewellery",
    price: 29,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
    redirectUrl: "https://example.com/product/zara-pearl-bracelet",
    tags: [],
    merchant: "Zara",
  },
  {
    id: 20,
    slug: "alexander-mcqueen-skull-ring",
    name: "Skull Crystal Cocktail Ring",
    brand: "Alexander McQueen",
    brandSlug: "alexander-mcqueen",
    category: "jewellery",
    categorySlug: "jewellery",
    price: 390,
    originalPrice: 520,
    image: "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=600&q=80",
    redirectUrl: "https://example.com/product/alexander-mcqueen-skull-ring",
    tags: ["sale", "trending"],
    merchant: "SSENSE",
  },
];

export const placeholderCoupons = [
  {
    id: 1,
    brand: "Zara",
    brandSlug: "zara",
    brandLogo: "/images/brands/zara.svg",
    code: "ZARA20",
    discount: "20% OFF",
    description: "20% off on all new season arrivals",
    expiryDate: "2026-04-30",
    redirectUrl: "https://example.com/coupon/zara20",
    type: "percentage",
  },
  {
    id: 2,
    brand: "H&M",
    brandSlug: "hm",
    brandLogo: "/images/brands/hm.svg",
    code: "HM15NOW",
    discount: "15% OFF",
    description: "15% off your first online order",
    expiryDate: "2026-05-15",
    redirectUrl: "https://example.com/coupon/hm15now",
    type: "percentage",
  },
  {
    id: 3,
    brand: "Adidas",
    brandSlug: "adidas",
    brandLogo: "/images/brands/adidas.svg",
    code: "ADISHIP",
    discount: "FREE SHIPPING",
    description: "Free standard shipping on all orders",
    expiryDate: "2026-04-15",
    redirectUrl: "https://example.com/coupon/adiship",
    type: "free-shipping",
  },
  {
    id: 4,
    brand: "Nike",
    brandSlug: "nike",
    brandLogo: "/images/brands/nike.svg",
    code: "NIKE25",
    discount: "25% OFF",
    description: "25% off select styles during seasonal sale",
    expiryDate: "2026-05-01",
    redirectUrl: "https://example.com/coupon/nike25",
    type: "percentage",
  },
  {
    id: 5,
    brand: "Gucci",
    brandSlug: "gucci",
    brandLogo: "/images/brands/gucci.svg",
    code: "GUCCI10",
    discount: "10% OFF",
    description: "10% off your first purchase over $500",
    expiryDate: "2026-06-30",
    redirectUrl: "https://example.com/coupon/gucci10",
    type: "percentage",
  },
  {
    id: 6,
    brand: "Prada",
    brandSlug: "prada",
    brandLogo: "/images/brands/prada.svg",
    code: "PRADA200",
    discount: "$200 OFF",
    description: "$200 off orders over $1500",
    expiryDate: "2026-05-31",
    redirectUrl: "https://example.com/coupon/prada200",
    type: "fixed",
  },
  {
    id: 7,
    brand: "Burberry",
    brandSlug: "burberry",
    brandLogo: "/images/brands/burberry.svg",
    code: "BURB15",
    discount: "15% OFF",
    description: "15% off heritage collection items",
    expiryDate: "2026-04-20",
    redirectUrl: "https://example.com/coupon/burb15",
    type: "percentage",
  },
  {
    id: 8,
    brand: "Fendi",
    brandSlug: "fendi",
    brandLogo: "/images/brands/fendi.svg",
    code: "FENDIFREE",
    discount: "FREE SHIPPING",
    description: "Complimentary shipping on all Fendi orders",
    expiryDate: "2026-06-15",
    redirectUrl: "https://example.com/coupon/fendifree",
    type: "free-shipping",
  },
  {
    id: 9,
    brand: "Mango",
    brandSlug: "mango",
    brandLogo: "/images/brands/mango.svg",
    code: "MANGO30",
    discount: "30% OFF",
    description: "30% off all outlet items",
    expiryDate: "2026-04-10",
    redirectUrl: "https://example.com/coupon/mango30",
    type: "percentage",
  },
  {
    id: 10,
    brand: "Michael Kors",
    brandSlug: "michael-kors",
    brandLogo: "/images/brands/michael-kors.svg",
    code: "MK50OFF",
    discount: "$50 OFF",
    description: "$50 off handbags and accessories over $200",
    expiryDate: "2026-05-20",
    redirectUrl: "https://example.com/coupon/mk50off",
    type: "fixed",
  },
  {
    id: 11,
    brand: "ASOS",
    brandSlug: "asos",
    brandLogo: "/images/brands/asos.svg",
    code: "ASOS20NEW",
    discount: "20% OFF",
    description: "20% off everything for new customers",
    expiryDate: "2026-07-01",
    redirectUrl: "https://example.com/coupon/asos20new",
    type: "percentage",
  },
  {
    id: 12,
    brand: "Net-a-Porter",
    brandSlug: "net-a-porter",
    brandLogo: "/images/brands/net-a-porter.svg",
    code: "NAP15SALE",
    discount: "15% OFF",
    description: "Extra 15% off sale items",
    expiryDate: "2026-04-25",
    redirectUrl: "https://example.com/coupon/nap15sale",
    type: "percentage",
  },
];

export const placeholderCategories = [
  {
    name: "Clothing",
    slug: "clothing",
    image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&q=80",
    productCount: 45,
  },
  {
    name: "Shoes",
    slug: "shoes",
    image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&q=80",
    productCount: 32,
  },
  {
    name: "Bags",
    slug: "bags",
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=600&q=80",
    productCount: 28,
  },
  {
    name: "Jewellery",
    slug: "jewellery",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    productCount: 19,
  },
];

export const placeholderBrands = [
  {
    id: 1,
    name: "Gucci",
    slug: "gucci",
    logo: "/images/brands/gucci.svg",
    productCount: 8,
    couponCount: 1,
    description: "Italian luxury house known for eclectic, contemporary designs and iconic GG monogram.",
  },
  {
    id: 2,
    name: "Prada",
    slug: "prada",
    logo: "/images/brands/prada.svg",
    productCount: 6,
    couponCount: 1,
    description: "Milanese fashion powerhouse blending intellectual design with luxury craftsmanship since 1913.",
  },
  {
    id: 3,
    name: "Burberry",
    slug: "burberry",
    logo: "/images/brands/burberry.svg",
    productCount: 7,
    couponCount: 1,
    description: "British heritage brand celebrated for its iconic check pattern and timeless trench coats.",
  },
  {
    id: 4,
    name: "Nike",
    slug: "nike",
    logo: "/images/brands/nike.svg",
    productCount: 10,
    couponCount: 1,
    description: "World-leading sportswear brand fusing athletic performance with street-ready style.",
  },
  {
    id: 5,
    name: "Zara",
    slug: "zara",
    logo: "/images/brands/zara.svg",
    productCount: 12,
    couponCount: 1,
    description: "Fast-fashion pioneer delivering runway-inspired pieces at accessible price points.",
  },
  {
    id: 6,
    name: "Fendi",
    slug: "fendi",
    logo: "/images/brands/fendi.svg",
    productCount: 5,
    couponCount: 1,
    description: "Roman luxury house renowned for fur craftsmanship, the Baguette bag, and bold FF logo.",
  },
  {
    id: 7,
    name: "Alexander McQueen",
    slug: "alexander-mcqueen",
    logo: "/images/brands/alexander-mcqueen.svg",
    productCount: 4,
    couponCount: 0,
    description: "Avant-garde British label known for dramatic silhouettes and signature oversized sneakers.",
  },
  {
    id: 8,
    name: "Michael Kors",
    slug: "michael-kors",
    logo: "/images/brands/michael-kors.svg",
    productCount: 6,
    couponCount: 1,
    description: "American designer offering jet-set luxury across ready-to-wear, accessories, and footwear.",
  },
  {
    id: 9,
    name: "Adidas",
    slug: "adidas",
    logo: "/images/brands/adidas.svg",
    productCount: 8,
    couponCount: 1,
    description: "German sportswear giant merging athletic innovation with streetwear culture since 1949.",
  },
  {
    id: 10,
    name: "H&M",
    slug: "hm",
    logo: "/images/brands/hm.svg",
    productCount: 14,
    couponCount: 1,
    description: "Swedish fashion retailer offering trend-driven clothing and accessories for every budget.",
  },
  {
    id: 11,
    name: "Mango",
    slug: "mango",
    logo: "/images/brands/mango.svg",
    productCount: 9,
    couponCount: 1,
    description: "Barcelona-based brand known for Mediterranean-inspired fashion with a modern edge.",
  },
  {
    id: 12,
    name: "Kenzo",
    slug: "kenzo",
    logo: "/images/brands/kenzo.svg",
    productCount: 5,
    couponCount: 0,
    description: "Parisian maison blending Japanese heritage with bold prints and vibrant colour palettes.",
  },
];

export const placeholderBlogPosts = [
  {
    id: 1,
    slug: "top-luxury-bags-spring-2026",
    title: "Top 10 Luxury Bags to Invest In This Spring",
    excerpt:
      "From the Fendi Baguette to the Gucci Marmont, these are the designer bags worth adding to your collection this season.",
    image: "https://images.unsplash.com/photo-1614179689702-355944cd0918?w=600&q=80",
    date: "2026-03-05",
    category: "Style Guide",
  },
  {
    id: 2,
    slug: "how-to-style-oversized-blazers",
    title: "How to Style Oversized Blazers for Every Occasion",
    excerpt:
      "The oversized blazer is the most versatile piece in your wardrobe. Here are five ways to wear it from office to evening.",
    image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600&q=80",
    date: "2026-02-20",
    category: "Trends",
  },
  {
    id: 3,
    slug: "best-sneaker-deals-march-2026",
    title: "Best Sneaker Deals & Coupon Codes for March 2026",
    excerpt:
      "Score up to 30% off Nike, Adidas, and more with these exclusive coupon codes and limited-time offers.",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&q=80",
    date: "2026-03-01",
    category: "Deals",
  },
];

// Helper functions

export function getProductBySlug(slug) {
  return placeholderProducts.find((p) => p.slug === slug) || null;
}

export function getProductsByBrand(brandSlug) {
  return placeholderProducts.filter((p) => p.brandSlug === brandSlug);
}

export function getProductsByCategory(categorySlug) {
  return placeholderProducts.filter((p) => p.categorySlug === categorySlug);
}

export function getCouponsByBrand(brandSlug) {
  return placeholderCoupons.filter((c) => c.brandSlug === brandSlug);
}

export function getBrandBySlug(brandSlug) {
  return placeholderBrands.find((b) => b.slug === brandSlug) || null;
}

export function searchProducts(query) {
  const q = query.toLowerCase();
  return placeholderProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
  );
}

export function searchCoupons(query) {
  const q = query.toLowerCase();
  return placeholderCoupons.filter((c) => c.brand.toLowerCase().includes(q));
}
