export const placeholderProducts = [
  {
    id: 1,
    slug: "mcqueen-oversized-sneakers",
    name: "Oversized Sneakers",
    brand: "Alexander McQueen",
    brandSlug: "alexander-mcqueen",
    category: "shoes",
    categorySlug: "shoes",
    subcategory: "sneakers",
    price: 590,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=600&q=80",
    redirectUrl: "https://example.com/product/mcqueen-oversized-sneakers",
    tags: ["trending"],
    merchant: "Farfetch",
  },
  {
    id: 2,
    slug: "kenzo-tiger-sweatshirt",
    name: "Tiger Embroidered Sweatshirt",
    brand: "Kenzo",
    brandSlug: "kenzo",
    category: "clothing",
    categorySlug: "clothing",
    subcategory: "tops",
    price: 285,
    originalPrice: 380,
    image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&q=80",
    redirectUrl: "https://example.com/product/kenzo-tiger-sweatshirt",
    tags: ["sale"],
    merchant: "SSENSE",
  },
  {
    id: 3,
    slug: "michael-kors-jet-set-tote",
    name: "Jet Set Travel Tote",
    brand: "Michael Kors",
    brandSlug: "michael-kors",
    category: "bags",
    categorySlug: "bags",
    subcategory: "tote-bags",
    price: 298,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&q=80",
    redirectUrl: "https://example.com/product/michael-kors-jet-set-tote",
    tags: ["trending"],
    merchant: "Nordstrom",
  },
  {
    id: 4,
    slug: "burberry-trench-coat",
    name: "Kensington Heritage Trench Coat",
    brand: "Burberry",
    brandSlug: "burberry",
    category: "clothing",
    categorySlug: "clothing",
    subcategory: "coats-jackets",
    price: 2290,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80",
    redirectUrl: "https://example.com/product/burberry-trench-coat",
    tags: ["trending"],
    merchant: "Mytheresa",
  },
  {
    id: 5,
    slug: "fendi-baguette-bag",
    name: "Baguette Shoulder Bag",
    brand: "Fendi",
    brandSlug: "fendi",
    category: "bags",
    categorySlug: "bags",
    subcategory: "shoulder-bags",
    price: 1890,
    originalPrice: 2490,
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=600&q=80",
    redirectUrl: "https://example.com/product/fendi-baguette-bag",
    tags: ["sale"],
    merchant: "Net-a-Porter",
  },
  {
    id: 6,
    slug: "gucci-horsebit-loafers",
    name: "Horsebit Leather Loafers",
    brand: "Gucci",
    brandSlug: "gucci",
    category: "shoes",
    categorySlug: "shoes",
    subcategory: "flats",
    price: 890,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=600&q=80",
    redirectUrl: "https://example.com/product/gucci-horsebit-loafers",
    tags: ["trending"],
    merchant: "Farfetch",
  },
  {
    id: 7,
    slug: "prada-re-nylon-jacket",
    name: "Re-Nylon Cropped Jacket",
    brand: "Prada",
    brandSlug: "prada",
    category: "clothing",
    categorySlug: "clothing",
    subcategory: "coats-jackets",
    price: 1650,
    originalPrice: 2100,
    image: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80",
    redirectUrl: "https://example.com/product/prada-re-nylon-jacket",
    tags: ["sale"],
    merchant: "SSENSE",
  },
  {
    id: 8,
    slug: "nike-air-max-97",
    name: "Air Max 97 Gold Bullet",
    brand: "Nike",
    brandSlug: "nike",
    category: "shoes",
    categorySlug: "shoes",
    subcategory: "sneakers",
    price: 175,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80",
    redirectUrl: "https://example.com/product/nike-air-max-97",
    tags: ["trending"],
    merchant: "Jomashop.com",
  },
  {
    id: 9,
    slug: "zara-satin-midi-dress",
    name: "Satin Midi Dress",
    brand: "Zara",
    brandSlug: "zara",
    category: "clothing",
    categorySlug: "clothing",
    subcategory: "dresses",
    price: 69,
    originalPrice: 99,
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&q=80",
    redirectUrl: "https://example.com/product/zara-satin-midi-dress",
    tags: ["sale"],
    merchant: "Farfetch",
  },
  {
    id: 10,
    slug: "hm-wool-blend-blazer",
    name: "Wool Blend Oversized Blazer",
    brand: "H&M",
    brandSlug: "hm",
    category: "clothing",
    categorySlug: "clothing",
    subcategory: "coats-jackets",
    price: 59,
    originalPrice: 89,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&q=80",
    redirectUrl: "https://example.com/product/hm-wool-blend-blazer",
    tags: ["sale"],
    merchant: "MatchesFashion",
  },
  {
    id: 11,
    slug: "mango-leather-crossbody",
    name: "Quilted Leather Crossbody",
    brand: "Mango",
    brandSlug: "mango",
    category: "bags",
    categorySlug: "bags",
    subcategory: "crossbody-bags",
    price: 79,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    redirectUrl: "https://example.com/product/mango-leather-crossbody",
    tags: ["new"],
    merchant: "Nordstrom",
  },
  {
    id: 12,
    slug: "adidas-ultraboost-22",
    name: "Ultraboost 22 Running Shoes",
    brand: "Adidas",
    brandSlug: "adidas",
    category: "shoes",
    categorySlug: "shoes",
    subcategory: "sneakers",
    price: 140,
    originalPrice: 190,
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=600&q=80",
    redirectUrl: "https://example.com/product/adidas-ultraboost-22",
    tags: ["sale"],
    merchant: "Jomashop.com",
  },
  {
    id: 13,
    slug: "gucci-marmont-mini-bag",
    name: "GG Marmont Mini Bag",
    brand: "Gucci",
    brandSlug: "gucci",
    category: "bags",
    categorySlug: "bags",
    subcategory: "crossbody-bags",
    price: 1290,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1575032617751-6ddec2089882?w=600&q=80",
    redirectUrl: "https://example.com/product/gucci-marmont-mini-bag",
    tags: ["trending"],
    merchant: "Mytheresa",
  },
  {
    id: 14,
    slug: "little-marc-jacobs-snapshot-bag",
    name: "The Snapshot Camera Bag",
    brand: "Little Marc Jacobs",
    brandSlug: "little-marc-jacobs",
    category: "bags",
    categorySlug: "bags",
    subcategory: "crossbody-bags",
    price: 325,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=600&q=80",
    redirectUrl: "https://example.com/product/little-marc-jacobs-snapshot-bag",
    tags: ["new"],
    merchant: "Nordstrom",
  },
  {
    id: 15,
    slug: "burberry-check-scarf",
    name: "Giant Check Cashmere Scarf",
    brand: "Burberry",
    brandSlug: "burberry",
    category: "clothing",
    categorySlug: "clothing",
    subcategory: "knitwear",
    price: 520,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80",
    redirectUrl: "https://example.com/product/burberry-check-scarf",
    tags: ["new"],
    merchant: "Net-a-Porter",
  },
  {
    id: 16,
    slug: "fendi-gold-earrings",
    name: "F is Fendi Gold Drop Earrings",
    brand: "Fendi",
    brandSlug: "fendi",
    category: "jewellery",
    categorySlug: "jewellery",
    subcategory: "earrings",
    price: 490,
    originalPrice: 650,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&q=80",
    redirectUrl: "https://example.com/product/fendi-gold-earrings",
    tags: ["sale"],
    merchant: "Farfetch",
  },
  {
    id: 17,
    slug: "prada-chain-necklace",
    name: "Eternal Gold Chain Necklace",
    brand: "Prada",
    brandSlug: "prada",
    category: "jewellery",
    categorySlug: "jewellery",
    subcategory: "necklaces",
    price: 2800,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    redirectUrl: "https://example.com/product/prada-chain-necklace",
    tags: [],
    merchant: "Mytheresa",
  },
  {
    id: 18,
    slug: "nike-dunk-low-panda",
    name: "Dunk Low Retro Panda",
    brand: "Nike",
    brandSlug: "nike",
    category: "shoes",
    categorySlug: "shoes",
    subcategory: "sneakers",
    price: 110,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=600&q=80",
    redirectUrl: "https://example.com/product/nike-dunk-low-panda",
    tags: ["new"],
    merchant: "Jomashop.com",
  },
  {
    id: 19,
    slug: "zara-pearl-bracelet",
    name: "Faux Pearl Link Bracelet",
    brand: "Zara",
    brandSlug: "zara",
    category: "jewellery",
    categorySlug: "jewellery",
    subcategory: "bracelets",
    price: 29,
    originalPrice: null,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80",
    redirectUrl: "https://example.com/product/zara-pearl-bracelet",
    tags: [],
    merchant: "MatchesFashion",
  },
  {
    id: 20,
    slug: "alexander-mcqueen-skull-ring",
    name: "Skull Crystal Cocktail Ring",
    brand: "Alexander McQueen",
    brandSlug: "alexander-mcqueen",
    category: "jewellery",
    categorySlug: "jewellery",
    subcategory: "rings",
    price: 390,
    originalPrice: 520,
    image: "https://images.unsplash.com/photo-1603561596112-0a132b757442?w=600&q=80",
    redirectUrl: "https://example.com/product/alexander-mcqueen-skull-ring",
    tags: ["sale", "trending"],
    merchant: "SSENSE",
  },
];

export const placeholderCoupons = [
  // ── ZARA ──
  {
    id: "coupon-zara-1",
    brand: "Zara",
    brandSlug: "zara",
    brandLogo: "/images/brands/zara.svg",
    code: "ZARA20",
    discount: "20% OFF",
    discountValue: "20%",
    discountLabel: "OFF",
    discountHeadline: "Extra 20% Off New Season Arrivals",
    description: "On minimum purchase of $100 or more. Valid on new season collections including dresses, outerwear, and accessories. Cannot be combined with other offers.",
    expiryDate: "2026-04-30",
    redirectUrl: "https://www.zara.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-zara-2",
    brand: "Zara",
    brandSlug: "zara",
    brandLogo: "/images/brands/zara.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Free Shipping on Orders Over $50",
    description: "Standard delivery at no cost on all orders over $50. Valid on full-price and sale items. Estimated delivery 3-7 business days.",
    expiryDate: "2026-06-30",
    redirectUrl: "https://www.zara.com",
    type: "free-shipping",
    status: "active",
  },
  {
    id: "coupon-zara-3",
    brand: "Zara",
    brandSlug: "zara",
    brandLogo: "/images/brands/zara.svg",
    discount: "30% OFF",
    discountValue: "30%",
    discountLabel: "OFF",
    discountHeadline: "30% Off Winter Collection",
    description: "Applied to all winter collection items including coats, knitwear, and boots. Online and in-store.",
    expiryDate: "2026-01-31",
    redirectUrl: "https://www.zara.com",
    type: "sale",
    status: "expired",
  },
  {
    id: "coupon-zara-4",
    brand: "Zara",
    brandSlug: "zara",
    brandLogo: "/images/brands/zara.svg",
    code: "ZARAAPP10",
    discount: "10% OFF",
    discountValue: "10%",
    discountLabel: "OFF",
    discountHeadline: "10% Off First App Purchase",
    description: "Download the Zara app and get 10% off your first order. Valid for new app users only.",
    expiryDate: "2025-12-15",
    redirectUrl: "https://www.zara.com",
    type: "coupon-code",
    status: "expired",
  },

  // ── H&M ──
  {
    id: "coupon-hm-1",
    brand: "H&M",
    brandSlug: "hm",
    brandLogo: "/images/brands/hm.svg",
    code: "HM15NOW",
    discount: "15% OFF",
    discountValue: "15%",
    discountLabel: "OFF",
    discountHeadline: "15% Off Your First Online Order",
    description: "Valid for new customers only. Applies to full-price and sale items across all categories. Cannot be combined with other promotional offers.",
    expiryDate: "2026-05-15",
    redirectUrl: "https://www.hm.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-hm-2",
    brand: "H&M",
    brandSlug: "hm",
    brandLogo: "/images/brands/hm.svg",
    discount: "BUY 2 GET 1",
    discountValue: "B2G1",
    discountLabel: "FREE",
    discountHeadline: "Buy 2 Get 1 Free on Basics",
    description: "Mix and match from the basics collection. Lowest priced item is free. Online only.",
    expiryDate: "2026-05-31",
    redirectUrl: "https://www.hm.com",
    type: "sale",
    status: "active",
  },
  {
    id: "coupon-hm-3",
    brand: "H&M",
    brandSlug: "hm",
    brandLogo: "/images/brands/hm.svg",
    code: "HMMEMBER25",
    discount: "25% OFF",
    discountValue: "25%",
    discountLabel: "OFF",
    discountHeadline: "25% Off Everything — Members Only",
    description: "Exclusive member discount on all items. Must be signed in to H&M account. One use per customer.",
    expiryDate: "2026-02-14",
    redirectUrl: "https://www.hm.com",
    type: "coupon-code",
    status: "expired",
  },
  {
    id: "coupon-hm-4",
    brand: "H&M",
    brandSlug: "hm",
    brandLogo: "/images/brands/hm.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Free Shipping Weekend",
    description: "No minimum order required. Valid Friday to Sunday only. Standard delivery.",
    expiryDate: "2026-01-12",
    redirectUrl: "https://www.hm.com",
    type: "free-shipping",
    status: "expired",
  },

  // ── ADIDAS ──
  {
    id: "coupon-adidas-1",
    brand: "Adidas",
    brandSlug: "adidas",
    brandLogo: "/images/brands/adidas.svg",
    code: "ADISHIP",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Free Standard Shipping on All Orders",
    description: "No minimum purchase required. Standard delivery 3-5 business days. Applies to all items including sale and clearance. Express shipping upgrade available at checkout.",
    expiryDate: "2026-04-15",
    redirectUrl: "https://www.adidas.com",
    type: "free-shipping",
    status: "active",
  },
  {
    id: "coupon-adidas-2",
    brand: "Adidas",
    brandSlug: "adidas",
    brandLogo: "/images/brands/adidas.svg",
    code: "ADI20FULL",
    discount: "20% OFF",
    discountValue: "20%",
    discountLabel: "OFF",
    discountHeadline: "20% Off Full-Price Styles",
    description: "Valid on full-price items only. Excludes collaborations and limited editions. Use code at checkout.",
    expiryDate: "2026-07-15",
    redirectUrl: "https://www.adidas.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-adidas-3",
    brand: "Adidas",
    brandSlug: "adidas",
    brandLogo: "/images/brands/adidas.svg",
    discount: "40% OFF",
    discountValue: "40%",
    discountLabel: "OFF",
    discountHeadline: "40% Off End of Season Sale",
    description: "Major markdowns across all categories. While stocks last. Cannot be combined with other offers.",
    expiryDate: "2026-01-20",
    redirectUrl: "https://www.adidas.com",
    type: "sale",
    status: "expired",
  },
  {
    id: "coupon-adidas-4",
    brand: "Adidas",
    brandSlug: "adidas",
    brandLogo: "/images/brands/adidas.svg",
    code: "ULTRA15",
    discount: "15% OFF",
    discountValue: "15%",
    discountLabel: "OFF",
    discountHeadline: "15% Off Ultraboost Collection",
    description: "Applied to all Ultraboost models including Ultraboost 22 and Ultraboost Light. Limited time.",
    expiryDate: "2025-11-30",
    redirectUrl: "https://www.adidas.com",
    type: "coupon-code",
    status: "expired",
  },

  // ── NIKE ──
  {
    id: "coupon-nike-1",
    brand: "Nike",
    brandSlug: "nike",
    brandLogo: "/images/brands/nike.svg",
    code: "NIKE25",
    discount: "25% OFF",
    discountValue: "25%",
    discountLabel: "OFF",
    discountHeadline: "25% Off Select Styles During Seasonal Sale",
    description: "Applies to selected items marked with sale tag. Includes Air Max, Dunk, and Jordan collections. While stocks last. Cannot be applied retroactively to previous orders.",
    expiryDate: "2026-05-01",
    redirectUrl: "https://www.nike.com",
    type: "sale",
    status: "active",
  },
  {
    id: "coupon-nike-2",
    brand: "Nike",
    brandSlug: "nike",
    brandLogo: "/images/brands/nike.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Free Shipping for Nike Members",
    description: "Join Nike membership for free and get complimentary shipping on every order. No minimum purchase.",
    expiryDate: "2026-12-31",
    redirectUrl: "https://www.nike.com",
    type: "free-shipping",
    status: "active",
  },
  {
    id: "coupon-nike-3",
    brand: "Nike",
    brandSlug: "nike",
    brandLogo: "/images/brands/nike.svg",
    discount: "30% OFF",
    discountValue: "30%",
    discountLabel: "OFF",
    discountHeadline: "30% Off Air Max Day Sale",
    description: "Celebrating Air Max Day with 30% off all Air Max styles. One day only event.",
    expiryDate: "2026-03-26",
    redirectUrl: "https://www.nike.com",
    type: "sale",
    status: "expired",
  },
  {
    id: "coupon-nike-4",
    brand: "Nike",
    brandSlug: "nike",
    brandLogo: "/images/brands/nike.svg",
    code: "NIKE20OFF",
    discount: "$20 OFF",
    discountValue: "$20",
    discountLabel: "OFF",
    discountHeadline: "$20 Off Orders Over $100",
    description: "On minimum spend of $100. Full-price and sale items. One use per account.",
    expiryDate: "2026-02-28",
    redirectUrl: "https://www.nike.com",
    type: "coupon-code",
    status: "expired",
  },

  // ── GUCCI ──
  {
    id: "coupon-gucci-1",
    brand: "Gucci",
    brandSlug: "gucci",
    brandLogo: "/images/brands/gucci.svg",
    code: "GUCCI10",
    discount: "10% OFF",
    discountValue: "10%",
    discountLabel: "OFF",
    discountHeadline: "10% Off Your First Purchase Over $500",
    description: "On minimum purchase of $500 or more. Applies to ready-to-wear, accessories, and shoes. Excludes beauty, fragrances, and gift cards.",
    expiryDate: "2026-06-30",
    redirectUrl: "https://www.gucci.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-gucci-2",
    brand: "Gucci",
    brandSlug: "gucci",
    brandLogo: "/images/brands/gucci.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Complimentary Express Shipping",
    description: "Free express delivery on all orders. Gift wrapping also available at no extra charge.",
    expiryDate: "2026-08-31",
    redirectUrl: "https://www.gucci.com",
    type: "free-shipping",
    status: "active",
  },
  {
    id: "coupon-gucci-3",
    brand: "Gucci",
    brandSlug: "gucci",
    brandLogo: "/images/brands/gucci.svg",
    discount: "15% OFF",
    discountValue: "15%",
    discountLabel: "OFF",
    discountHeadline: "15% Off Private Sale",
    description: "By invitation only. Valid on selected ready-to-wear and accessories. Cannot be combined with other offers.",
    expiryDate: "2026-01-15",
    redirectUrl: "https://www.gucci.com",
    type: "sale",
    status: "expired",
  },
  {
    id: "coupon-gucci-4",
    brand: "Gucci",
    brandSlug: "gucci",
    brandLogo: "/images/brands/gucci.svg",
    code: "GUCCI100",
    discount: "$100 OFF",
    discountValue: "$100",
    discountLabel: "OFF",
    discountHeadline: "$100 Off Accessories Over $800",
    description: "Valid on bags, belts, wallets, and small leather goods. Minimum purchase $800.",
    expiryDate: "2025-12-31",
    redirectUrl: "https://www.gucci.com",
    type: "coupon-code",
    status: "expired",
  },

  // ── PRADA ──
  {
    id: "coupon-prada-1",
    brand: "Prada",
    brandSlug: "prada",
    brandLogo: "/images/brands/prada.svg",
    code: "PRADA200",
    discount: "$200 OFF",
    discountValue: "$200",
    discountLabel: "OFF",
    discountHeadline: "$200 Off Orders Over $1500",
    description: "On minimum purchase of $1500 or more. Full-price items only. Valid on bags, shoes, ready-to-wear, and accessories. One use per customer.",
    expiryDate: "2026-05-31",
    redirectUrl: "https://www.prada.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-prada-2",
    brand: "Prada",
    brandSlug: "prada",
    brandLogo: "/images/brands/prada.svg",
    discount: "10% OFF",
    discountValue: "10%",
    discountLabel: "OFF",
    discountHeadline: "10% Off Re-Nylon Collection",
    description: "Valid on all Re-Nylon bags and accessories. Sustainable luxury at a discount.",
    expiryDate: "2026-06-15",
    redirectUrl: "https://www.prada.com",
    type: "sale",
    status: "active",
  },
  {
    id: "coupon-prada-3",
    brand: "Prada",
    brandSlug: "prada",
    brandLogo: "/images/brands/prada.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Free Priority Shipping",
    description: "Complimentary priority shipping on all orders during holiday season. Gift wrapping included.",
    expiryDate: "2025-12-25",
    redirectUrl: "https://www.prada.com",
    type: "free-shipping",
    status: "expired",
  },
  {
    id: "coupon-prada-4",
    brand: "Prada",
    brandSlug: "prada",
    brandLogo: "/images/brands/prada.svg",
    discount: "20% OFF",
    discountValue: "20%",
    discountLabel: "OFF",
    discountHeadline: "20% Off Outlet Items",
    description: "Additional 20% off already reduced outlet prices. Final sale, no returns.",
    expiryDate: "2026-02-10",
    redirectUrl: "https://www.prada.com",
    type: "sale",
    status: "expired",
  },

  // ── BURBERRY ──
  {
    id: "coupon-burberry-1",
    brand: "Burberry",
    brandSlug: "burberry",
    brandLogo: "/images/brands/burberry.svg",
    code: "BURB15",
    discount: "15% OFF",
    discountValue: "15%",
    discountLabel: "OFF",
    discountHeadline: "15% Off Heritage Collection Items",
    description: "Valid on trench coats, scarves, and heritage check accessories. Includes the iconic Kensington and Chelsea styles. Limited time offer.",
    expiryDate: "2026-04-20",
    redirectUrl: "https://www.burberry.com",
    type: "sale",
    status: "active",
  },
  {
    id: "coupon-burberry-2",
    brand: "Burberry",
    brandSlug: "burberry",
    brandLogo: "/images/brands/burberry.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Complimentary Shipping & Returns",
    description: "Free standard shipping and free returns on all orders. No minimum purchase required.",
    expiryDate: "2026-09-30",
    redirectUrl: "https://www.burberry.com",
    type: "free-shipping",
    status: "active",
  },
  {
    id: "coupon-burberry-3",
    brand: "Burberry",
    brandSlug: "burberry",
    brandLogo: "/images/brands/burberry.svg",
    discount: "25% OFF",
    discountValue: "25%",
    discountLabel: "OFF",
    discountHeadline: "25% Off Outerwear",
    description: "Valid on all trench coats, puffer jackets, and car coats. Limited time seasonal offer.",
    expiryDate: "2026-01-31",
    redirectUrl: "https://www.burberry.com",
    type: "sale",
    status: "expired",
  },
  {
    id: "coupon-burberry-4",
    brand: "Burberry",
    brandSlug: "burberry",
    brandLogo: "/images/brands/burberry.svg",
    code: "BURB150",
    discount: "$150 OFF",
    discountValue: "$150",
    discountLabel: "OFF",
    discountHeadline: "$150 Off Scarves & Accessories",
    description: "On minimum purchase of $500 in the scarves and accessories category.",
    expiryDate: "2025-11-15",
    redirectUrl: "https://www.burberry.com",
    type: "coupon-code",
    status: "expired",
  },

  // ── FENDI ──
  {
    id: "coupon-fendi-1",
    brand: "Fendi",
    brandSlug: "fendi",
    brandLogo: "/images/brands/fendi.svg",
    code: "FENDIFREE",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Complimentary Shipping on All Fendi Orders",
    description: "Express delivery included at no extra cost. No minimum purchase required. Covers all categories including bags, accessories, and ready-to-wear.",
    expiryDate: "2026-06-15",
    redirectUrl: "https://www.fendi.com",
    type: "free-shipping",
    status: "active",
  },
  {
    id: "coupon-fendi-2",
    brand: "Fendi",
    brandSlug: "fendi",
    brandLogo: "/images/brands/fendi.svg",
    discount: "10% OFF",
    discountValue: "10%",
    discountLabel: "OFF",
    discountHeadline: "10% Off Peekaboo & Baguette Bags",
    description: "Valid on iconic Fendi bag collections. Includes all sizes and colors in current season.",
    expiryDate: "2026-07-31",
    redirectUrl: "https://www.fendi.com",
    type: "sale",
    status: "active",
  },
  {
    id: "coupon-fendi-3",
    brand: "Fendi",
    brandSlug: "fendi",
    brandLogo: "/images/brands/fendi.svg",
    code: "FENDI20PF",
    discount: "20% OFF",
    discountValue: "20%",
    discountLabel: "OFF",
    discountHeadline: "20% Off Pre-Fall Collection",
    description: "Early access to pre-fall pieces with 20% discount. For registered customers only.",
    expiryDate: "2026-02-28",
    redirectUrl: "https://www.fendi.com",
    type: "coupon-code",
    status: "expired",
  },
  {
    id: "coupon-fendi-4",
    brand: "Fendi",
    brandSlug: "fendi",
    brandLogo: "/images/brands/fendi.svg",
    code: "FENDI50SLG",
    discount: "$50 OFF",
    discountValue: "$50",
    discountLabel: "OFF",
    discountHeadline: "$50 Off Small Leather Goods",
    description: "Valid on wallets, card holders, and key rings. Minimum purchase $200.",
    expiryDate: "2025-12-20",
    redirectUrl: "https://www.fendi.com",
    type: "coupon-code",
    status: "expired",
  },

  // ── MANGO ──
  {
    id: "coupon-mango-1",
    brand: "Mango",
    brandSlug: "mango",
    brandLogo: "/images/brands/mango.svg",
    code: "MANGO30",
    discount: "30% OFF",
    discountValue: "30%",
    discountLabel: "OFF",
    discountHeadline: "30% Off All Outlet Items",
    description: "On outlet section items only. Cannot be combined with other discounts. Includes last-season collections across clothing, shoes, bags, and jewellery.",
    expiryDate: "2026-04-10",
    redirectUrl: "https://www.mango.com",
    type: "sale",
    status: "active",
  },
  {
    id: "coupon-mango-2",
    brand: "Mango",
    brandSlug: "mango",
    brandLogo: "/images/brands/mango.svg",
    code: "MANGO15NEW",
    discount: "15% OFF",
    discountValue: "15%",
    discountLabel: "OFF",
    discountHeadline: "15% Off New Collection",
    description: "Valid on all new arrivals. Cannot be combined with other promotions. Online only.",
    expiryDate: "2026-05-15",
    redirectUrl: "https://www.mango.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-mango-3",
    brand: "Mango",
    brandSlug: "mango",
    brandLogo: "/images/brands/mango.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Free Shipping All Weekend",
    description: "No code needed. Applied automatically at checkout. Standard delivery only.",
    expiryDate: "2026-01-05",
    redirectUrl: "https://www.mango.com",
    type: "free-shipping",
    status: "expired",
  },
  {
    id: "coupon-mango-4",
    brand: "Mango",
    brandSlug: "mango",
    brandLogo: "/images/brands/mango.svg",
    discount: "40% OFF",
    discountValue: "40%",
    discountLabel: "OFF",
    discountHeadline: "40% Off Mid-Season Sale",
    description: "Huge markdowns across all categories. While stocks last. In-store and online.",
    expiryDate: "2026-02-20",
    redirectUrl: "https://www.mango.com",
    type: "sale",
    status: "expired",
  },

  // ── MICHAEL KORS ──
  {
    id: "coupon-mk-1",
    brand: "Michael Kors",
    brandSlug: "michael-kors",
    brandLogo: "/images/brands/michael-kors.svg",
    code: "MK50OFF",
    discount: "$50 OFF",
    discountValue: "$50",
    discountLabel: "OFF",
    discountHeadline: "$50 Off Handbags and Accessories",
    description: "On minimum purchase of $200 or more. Handbags and accessories only. Includes Jet Set, Parker, and Soho collections.",
    expiryDate: "2026-05-20",
    redirectUrl: "https://www.michaelkors.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-mk-2",
    brand: "Michael Kors",
    brandSlug: "michael-kors",
    brandLogo: "/images/brands/michael-kors.svg",
    code: "MK25FULL",
    discount: "25% OFF",
    discountValue: "25%",
    discountLabel: "OFF",
    discountHeadline: "25% Off Full-Price Styles",
    description: "Sitewide discount on all full-price items. Includes bags, watches, and clothing.",
    expiryDate: "2026-06-30",
    redirectUrl: "https://www.michaelkors.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-mk-3",
    brand: "Michael Kors",
    brandSlug: "michael-kors",
    brandLogo: "/images/brands/michael-kors.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Free Express Shipping",
    description: "Complimentary express delivery on all orders over $150. Holiday special.",
    expiryDate: "2025-12-31",
    redirectUrl: "https://www.michaelkors.com",
    type: "free-shipping",
    status: "expired",
  },
  {
    id: "coupon-mk-4",
    brand: "Michael Kors",
    brandSlug: "michael-kors",
    brandLogo: "/images/brands/michael-kors.svg",
    discount: "50% OFF",
    discountValue: "50%",
    discountLabel: "OFF",
    discountHeadline: "50% Off Outlet Styles",
    description: "Additional 50% off all outlet items. Final sale. Cannot be returned or exchanged.",
    expiryDate: "2026-01-25",
    redirectUrl: "https://www.michaelkors.com",
    type: "sale",
    status: "expired",
  },

  // ── ASOS ──
  {
    id: "coupon-asos-1",
    brand: "ASOS",
    brandSlug: "asos",
    brandLogo: "/images/brands/asos.svg",
    code: "ASOS20NEW",
    discount: "2% BACK",
    discountValue: "2%",
    discountLabel: "BACK",
    discountHeadline: "2% Cash Back on Everything",
    description: "Earn 2% cash back on all purchases. Available for new and existing customers. Cash back credited within 30 business days of purchase confirmation.",
    expiryDate: "2026-07-01",
    redirectUrl: "https://www.asos.com",
    type: "cashback",
    status: "active",
  },
  {
    id: "coupon-asos-2",
    brand: "ASOS",
    brandSlug: "asos",
    brandLogo: "/images/brands/asos.svg",
    code: "ASOSNEW20",
    discount: "20% OFF",
    discountValue: "20%",
    discountLabel: "OFF",
    discountHeadline: "20% Off Everything for New Customers",
    description: "First-time shoppers only. Valid on full-price and sale items. One use per customer.",
    expiryDate: "2026-08-31",
    redirectUrl: "https://www.asos.com",
    type: "coupon-code",
    status: "active",
  },
  {
    id: "coupon-asos-3",
    brand: "ASOS",
    brandSlug: "asos",
    brandLogo: "/images/brands/asos.svg",
    code: "ASOSAPP30",
    discount: "30% OFF",
    discountValue: "30%",
    discountLabel: "OFF",
    discountHeadline: "30% Off App Exclusive",
    description: "Download the ASOS app and get 30% off your first app order. New app users only.",
    expiryDate: "2026-02-14",
    redirectUrl: "https://www.asos.com",
    type: "coupon-code",
    status: "expired",
  },
  {
    id: "coupon-asos-4",
    brand: "ASOS",
    brandSlug: "asos",
    brandLogo: "/images/brands/asos.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Free Next-Day Delivery",
    description: "Premier members get free next-day delivery on all orders. Limited time trial offer.",
    expiryDate: "2025-12-01",
    redirectUrl: "https://www.asos.com",
    type: "free-shipping",
    status: "expired",
  },

  // ── NET-A-PORTER ──
  {
    id: "coupon-nap-1",
    brand: "Net-a-Porter",
    brandSlug: "net-a-porter",
    brandLogo: "/images/brands/net-a-porter.svg",
    code: "NAP15SALE",
    discount: "15% OFF",
    discountValue: "15%",
    discountLabel: "OFF",
    discountHeadline: "Extra 15% Off Sale Items",
    description: "Applies to already-reduced sale items. Limited time offer. Includes designer clothing, shoes, bags, and jewellery from over 800 brands.",
    expiryDate: "2026-04-25",
    redirectUrl: "https://www.net-a-porter.com",
    type: "sale",
    status: "active",
  },
  {
    id: "coupon-nap-2",
    brand: "Net-a-Porter",
    brandSlug: "net-a-porter",
    brandLogo: "/images/brands/net-a-porter.svg",
    discount: "FREE SHIPPING",
    discountValue: "FREE",
    discountLabel: "SHIPPING",
    discountHeadline: "Complimentary Express Shipping",
    description: "Free express delivery on all orders. Same-day delivery available in select cities.",
    expiryDate: "2026-09-30",
    redirectUrl: "https://www.net-a-porter.com",
    type: "free-shipping",
    status: "active",
  },
  {
    id: "coupon-nap-3",
    brand: "Net-a-Porter",
    brandSlug: "net-a-porter",
    brandLogo: "/images/brands/net-a-porter.svg",
    discount: "20% OFF",
    discountValue: "20%",
    discountLabel: "OFF",
    discountHeadline: "20% Off EIP Private Sale",
    description: "Exclusive access for EIP members. Valid on selected designer pieces across all categories.",
    expiryDate: "2026-01-20",
    redirectUrl: "https://www.net-a-porter.com",
    type: "sale",
    status: "expired",
  },
  {
    id: "coupon-nap-4",
    brand: "Net-a-Porter",
    brandSlug: "net-a-porter",
    brandLogo: "/images/brands/net-a-porter.svg",
    code: "NAP75WELCOME",
    discount: "$75 OFF",
    discountValue: "$75",
    discountLabel: "OFF",
    discountHeadline: "$75 Off Your First Order Over $400",
    description: "Welcome offer for new customers. Minimum spend $400. Full-price items only.",
    expiryDate: "2025-11-30",
    redirectUrl: "https://www.net-a-porter.com",
    type: "coupon-code",
    status: "expired",
  },
];

export const placeholderCategories = [
  {
    name: "Clothing",
    slug: "clothing",
    image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&q=80",
    productCount: 45,
  },
  {
    name: "Shoes",
    slug: "shoes",
    image: "https://images.unsplash.com/photo-1560343090-f0409e92791a?w=600&q=80",
    productCount: 32,
  },
  {
    name: "Bags",
    slug: "bags",
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=600&q=80",
    productCount: 28,
  },
  {
    name: "Jewellery",
    slug: "jewellery",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&q=80",
    productCount: 19,
  },
];

export const placeholderBrands = [
  {
    id: 1,
    name: "Gucci",
    slug: "gucci",
    logo: "/images/brands/gucci.svg",
    productCount: 8,
    couponCount: 1,
    description: "Italian luxury house known for eclectic, contemporary designs and iconic GG monogram.",
  },
  {
    id: 2,
    name: "Prada",
    slug: "prada",
    logo: "/images/brands/prada.svg",
    productCount: 6,
    couponCount: 1,
    description: "Milanese fashion powerhouse blending intellectual design with luxury craftsmanship since 1913.",
  },
  {
    id: 3,
    name: "Burberry",
    slug: "burberry",
    logo: "/images/brands/burberry.svg",
    productCount: 7,
    couponCount: 1,
    description: "British heritage brand celebrated for its iconic check pattern and timeless trench coats.",
  },
  {
    id: 4,
    name: "Nike",
    slug: "nike",
    logo: "/images/brands/nike.svg",
    productCount: 10,
    couponCount: 1,
    description: "World-leading sportswear brand fusing athletic performance with street-ready style.",
  },
  {
    id: 5,
    name: "Zara",
    slug: "zara",
    logo: "/images/brands/zara.svg",
    productCount: 12,
    couponCount: 1,
    description: "Fast-fashion pioneer delivering runway-inspired pieces at accessible price points.",
  },
  {
    id: 6,
    name: "Fendi",
    slug: "fendi",
    logo: "/images/brands/fendi.svg",
    productCount: 5,
    couponCount: 1,
    description: "Roman luxury house renowned for fur craftsmanship, the Baguette bag, and bold FF logo.",
  },
  {
    id: 7,
    name: "Alexander McQueen",
    slug: "alexander-mcqueen",
    logo: "/images/brands/alexander-mcqueen.svg",
    productCount: 4,
    couponCount: 0,
    description: "Avant-garde British label known for dramatic silhouettes and signature oversized sneakers.",
  },
  {
    id: 8,
    name: "Michael Kors",
    slug: "michael-kors",
    logo: "/images/brands/michael-kors.svg",
    productCount: 6,
    couponCount: 1,
    description: "American designer offering jet-set luxury across ready-to-wear, accessories, and footwear.",
  },
  {
    id: 9,
    name: "Adidas",
    slug: "adidas",
    logo: "/images/brands/adidas.svg",
    productCount: 8,
    couponCount: 1,
    description: "German sportswear giant merging athletic innovation with streetwear culture since 1949.",
  },
  {
    id: 10,
    name: "H&M",
    slug: "hm",
    logo: "/images/brands/hm.svg",
    productCount: 14,
    couponCount: 1,
    description: "Swedish fashion retailer offering trend-driven clothing and accessories for every budget.",
  },
  {
    id: 11,
    name: "Mango",
    slug: "mango",
    logo: "/images/brands/mango.svg",
    productCount: 9,
    couponCount: 1,
    description: "Barcelona-based brand known for Mediterranean-inspired fashion with a modern edge.",
  },
  {
    id: 12,
    name: "Kenzo",
    slug: "kenzo",
    logo: "/images/brands/kenzo.svg",
    productCount: 5,
    couponCount: 0,
    description: "Parisian maison blending Japanese heritage with bold prints and vibrant colour palettes.",
  },
  {
    id: 13,
    name: "Valentino",
    slug: "valentino",
    logo: "/images/brands/valentino.svg",
    productCount: 6,
    couponCount: 0,
    description: "Italian haute couture house famous for Valentino Red and romantic, refined elegance.",
  },
  {
    id: 14,
    name: "Saint Laurent",
    slug: "saint-laurent",
    logo: "/images/brands/saint-laurent.svg",
    productCount: 5,
    couponCount: 0,
    description: "French luxury brand blending Parisian cool with rock-and-roll edge since 1961.",
  },
  {
    id: 15,
    name: "Balenciaga",
    slug: "balenciaga",
    logo: "/images/brands/balenciaga.svg",
    productCount: 7,
    couponCount: 0,
    description: "Spanish-founded fashion house known for avant-garde silhouettes and oversized designs.",
  },
  {
    id: 16,
    name: "Bottega Veneta",
    slug: "bottega-veneta",
    logo: "/images/brands/bottega-veneta.svg",
    productCount: 4,
    couponCount: 0,
    description: "Italian luxury brand celebrated for its signature intrecciato woven leather goods.",
  },
  {
    id: 17,
    name: "Celine",
    slug: "celine",
    logo: "/images/brands/celine.svg",
    productCount: 5,
    couponCount: 0,
    description: "French maison offering minimalist luxury with a focus on understated Parisian chic.",
  },
  {
    id: 18,
    name: "Chanel",
    slug: "chanel",
    logo: "/images/brands/chanel.svg",
    productCount: 3,
    couponCount: 0,
    description: "Iconic French fashion house synonymous with timeless elegance and the little black dress.",
  },
  {
    id: 19,
    name: "Dior",
    slug: "dior",
    logo: "/images/brands/dior.svg",
    productCount: 6,
    couponCount: 0,
    description: "French luxury brand known for the New Look silhouette and haute couture excellence.",
  },
  {
    id: 20,
    name: "Dolce & Gabbana",
    slug: "dolce-gabbana",
    logo: "/images/brands/dolce-gabbana.svg",
    productCount: 5,
    couponCount: 0,
    description: "Italian fashion duo celebrated for bold Mediterranean glamour and ornate designs.",
  },
  {
    id: 21,
    name: "Givenchy",
    slug: "givenchy",
    logo: "/images/brands/givenchy.svg",
    productCount: 4,
    couponCount: 0,
    description: "French couture house blending aristocratic elegance with modern streetwear influences.",
  },
  {
    id: 22,
    name: "Hermes",
    slug: "hermes",
    logo: "/images/brands/hermes.svg",
    productCount: 3,
    couponCount: 0,
    description: "French luxury house famed for the Birkin bag, silk scarves, and equestrian heritage.",
  },
  {
    id: 23,
    name: "Jimmy Choo",
    slug: "jimmy-choo",
    logo: "/images/brands/jimmy-choo.svg",
    productCount: 5,
    couponCount: 0,
    description: "British luxury brand synonymous with glamorous heels and red-carpet footwear.",
  },
  {
    id: 24,
    name: "Loewe",
    slug: "loewe",
    logo: "/images/brands/loewe.svg",
    productCount: 4,
    couponCount: 0,
    description: "Spanish luxury house known for exceptional leather craft and the Puzzle bag.",
  },
  {
    id: 25,
    name: "Louis Vuitton",
    slug: "louis-vuitton",
    logo: "/images/brands/louis-vuitton.svg",
    productCount: 6,
    couponCount: 0,
    description: "French luxury giant recognised worldwide for its monogram canvas and trunk-making heritage.",
  },
  {
    id: 26,
    name: "Miu Miu",
    slug: "miu-miu",
    logo: "/images/brands/miu-miu.svg",
    productCount: 4,
    couponCount: 0,
    description: "Prada's younger sister brand offering playful, feminine fashion with a rebellious twist.",
  },
  {
    id: 27,
    name: "Moschino",
    slug: "moschino",
    logo: "/images/brands/moschino.svg",
    productCount: 3,
    couponCount: 0,
    description: "Italian brand known for bold pop-art inspired designs and witty fashion statements.",
  },
  {
    id: 28,
    name: "Off-White",
    slug: "off-white",
    logo: "/images/brands/off-white.svg",
    productCount: 5,
    couponCount: 0,
    description: "Streetwear-meets-luxury label founded by Virgil Abloh, known for diagonal stripe motifs.",
  },
  {
    id: 29,
    name: "Stella McCartney",
    slug: "stella-mccartney",
    logo: "/images/brands/stella-mccartney.svg",
    productCount: 4,
    couponCount: 0,
    description: "British designer championing sustainable luxury fashion without leather or fur.",
  },
  {
    id: 30,
    name: "Tom Ford",
    slug: "tom-ford",
    logo: "/images/brands/tom-ford.svg",
    productCount: 3,
    couponCount: 0,
    description: "American designer offering sharp tailoring and sensual glamour across fashion and beauty.",
  },
  {
    id: 31,
    name: "Versace",
    slug: "versace",
    logo: "/images/brands/versace.svg",
    productCount: 5,
    couponCount: 0,
    description: "Italian luxury house defined by bold prints, the Medusa head, and unapologetic glamour.",
  },
  {
    id: 32,
    name: "Vivienne Westwood",
    slug: "vivienne-westwood",
    logo: "/images/brands/vivienne-westwood.svg",
    productCount: 4,
    couponCount: 0,
    description: "British punk pioneer turned haute couture icon, known for the orb logo and tartan.",
  },
];

export const placeholderBlogPosts = [
  {
    id: 1,
    slug: "top-luxury-bags-spring-2026",
    title: "Top 10 Luxury Bags to Invest In This Spring",
    excerpt:
      "From the Fendi Baguette to the Gucci Marmont, these are the designer bags worth adding to your collection this season.",
    image: "https://images.unsplash.com/photo-1614179689702-355944cd0918?w=600&q=80",
    date: "2026-03-05",
    category: "Style Guide",
  },
  {
    id: 2,
    slug: "how-to-style-oversized-blazers",
    title: "How to Style Oversized Blazers for Every Occasion",
    excerpt:
      "The oversized blazer is the most versatile piece in your wardrobe. Here are five ways to wear it from office to evening.",
    image: "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?w=600&q=80",
    date: "2026-02-20",
    category: "Trends",
  },
  {
    id: 3,
    slug: "best-sneaker-deals-march-2026",
    title: "Best Sneaker Deals & Coupon Codes for March 2026",
    excerpt:
      "Score up to 30% off Nike, Adidas, and more with these exclusive coupon codes and limited-time offers.",
    image: "https://images.unsplash.com/photo-1552346154-21d32810aba3?w=600&q=80",
    date: "2026-03-01",
    category: "Deals",
  },
];

// Helper functions

export function getProductBySlug(slug) {
  return placeholderProducts.find((p) => p.slug === slug) || null;
}

export function getProductsByBrand(brandSlug) {
  return placeholderProducts.filter((p) => p.brandSlug === brandSlug);
}

export function getProductsByCategory(categorySlug) {
  return placeholderProducts.filter((p) => p.categorySlug === categorySlug);
}

export function getCouponsByBrand(brandSlug) {
  return placeholderCoupons.filter((c) => c.brandSlug === brandSlug);
}

export function getActiveCouponsByBrand(brandSlug) {
  return placeholderCoupons.filter(
    (c) => c.brandSlug === brandSlug && c.status === "active"
  );
}

export function getExpiredCouponsByBrand(brandSlug) {
  return placeholderCoupons.filter(
    (c) => c.brandSlug === brandSlug && c.status === "expired"
  );
}

export function getActiveCoupons() {
  return placeholderCoupons.filter((c) => c.status === "active");
}

export function getBrandBySlug(brandSlug) {
  const brand = placeholderBrands.find((b) => b.slug === brandSlug);
  if (!brand) return null;
  return {
    ...brand,
    productCount: placeholderProducts.filter((p) => p.brandSlug === brandSlug).length,
    couponCount: placeholderCoupons.filter((c) => c.brandSlug === brandSlug && c.status === "active").length,
  };
}

export function searchProducts(query) {
  const q = query.toLowerCase();
  return placeholderProducts.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.brand.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q)
  );
}

export function searchCoupons(query) {
  const q = query.toLowerCase();
  return placeholderCoupons.filter(
    (c) => c.status === "active" && c.brand.toLowerCase().includes(q)
  );
}
